### ISSUE TITLE
Coterm Not Working Under Internal IP

### ISSUE THREAD

**Issue by leo852** [ConvoyPanel/coterm#3]
### Current Behavior

Coterm is Not Working Under Internal IP, it will show "not connected"
![Screenshot 2023-12-25 042015](https://github.com/ConvoyPanel/coterm/assets/33802295/f636fd71-2e72-46a6-9ae9-59806f1d2af6)
![Screenshot 2023-12-25 042031](https://github.com/ConvoyPanel/coterm/assets/33802295/a2b6e2d4-2a3b-4438-af31-a00fb6e82e41)

### Expected Behavior

Connects to novnc or xterm

### Steps to Reproduce

install coterm, pve, convoy on local network and connect them through internal ip

### Proxmox OS Version

8.1.3

### Operating System

Windows 11

### Browser

FIrefox

### Panel Version

4.0.0-rc3

### Coterm Version

1.1.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ericwang401** [comment]
Added in `v2.0.0`
